### ISSUE TITLE
The first def form is always show a plus symbol on the left

### ISSUE THREAD

**Issue by zhanghuabin** [zjhmale/intellij-clojure-pretty-symbol#3]
# Env
- Win 8.1
- IDEA Ultimate 15.0.4
- Clojure Pretty Symbol 1.3
- JDK 1.8
# Steps:
- Add two def forms.
- The first form will show a plus symbol.

Please see the screenshot.

![ss](https://cloud.githubusercontent.com/assets/5813426/13995812/cd290f70-f165-11e5-8737-7ff519106676.jpg)

**Comment by swr1bm86** [comment]
hey @zhanghuabin thx for reporting! i just fix it because i put all the symbols into a group. and there is no annoying plus symbol for now, you can update the plugin, Cheers! :tada: 

![2016-03-24 11 27 10](https://cloud.githubusercontent.com/assets/6234553/14008934/af8a7786-f1c1-11e5-9c65-af1b5917c838.png)

**Comment by zhanghuabin** [comment]
:+1: :tada:
