### ISSUE TITLE
let symbol is reset to let form when bindings are laying each on its line

### ISSUE THREAD

**Issue by rssole** [zjhmale/intellij-clojure-pretty-symbol#4]
This might not be an issue...maybe it is intentional but anyway for you to be aware for me in IDEA 15 with CPS 1.4, given: 
`(let [x 2 y 3]...` 
let is replaced with symbol.
However, if I put each binding on its own line like

```
(let [x 2
       y 3]...
```

symbol turns back to "let"...

If this is intentional then just close this issue.

Cheers!

**Comment by swr1bm86** [comment]
@rssole this is intentional cause if it dose not turns back to "let" it will cause a `Indent error`.
- the good indentation

``` clojure
(let [a 1
      b 2])
```
- the bad

``` clojure
(⊢ [a 1
       b 2])
```

so when the left and right delimiters not matching, the pretty symbols will not showing, so does `letfn`, `not=`, `doseq` etc.

**Comment by rssole** [comment]
Hi, please find attached images before and after switching to multiple lines bindings,
before, my indentation seems quite ok:
![image](https://cloud.githubusercontent.com/assets/3775275/14073416/1e500bfe-f4c9-11e5-83e2-5a703320d15e.png)
afterwards:
![image](https://cloud.githubusercontent.com/assets/3775275/14073431/678de2e6-f4c9-11e5-9395-55a958fc5610.png)

But, like I said, it is not really something problematic, I just wanted you to be aware of it.

Cheers

**Comment by rssole** [comment]
Ok right, makes sense :)

**Comment by tylerperkins** [comment]
How about this solution: In the few problematic indentation cases like **let**, just pad the pretty symbol with spaces so it doesn't disturb horizontal placement of text to the right. So

```
(let [
```

(six chars.) would be appear as

```
( ⊢  [
```

(also six chars.) I.e. "let" becomes " ⊢ " (note one space before ⊢ and one after, then the already-existing space comes after that). The result is the same size, but it's still small (since "let" is small), and there is less visual clutter. Besides, it's optional, of course!

**Comment by swr1bm86** [comment]
@tylerperkins good point! i will try to add it later :)
