### ISSUE TITLE
comp symbol not showing up

### ISSUE THREAD

**Issue by Engelberg** [zjhmale/intellij-clojure-pretty-symbol#7]
I installed the latest version of the plugin, which has an option for comp, but even with that enabled in my settings, I'm not seeing any symbol appear for comp.

**Comment by swr1bm86** [comment]
hi @Engelberg i got comp symbols here.

![image](https://cloud.githubusercontent.com/assets/6234553/14224170/77c7882e-f8c5-11e5-882a-aa681e1c463c.png)

and if i do not misunderstand you, you mean that after you enabled comp symbols in settings panel, they just not showing in the editor immediately right? i tried to make that happen when you click `apply` button, but due to an internal design of Intellij, we have to type something in the editor i.e. type enter, to see the changes from settings, here is a example, may that help you.

![snapshot](https://cloud.githubusercontent.com/assets/6234553/14224212/fce04d74-f8c6-11e5-8295-0234819d2e8b.gif)

**Comment by Engelberg** [comment]
I specifically mean the pretty comp symbol, just that one symbol. I type
the word comp and it doesn't get substituted.

**Comment by swr1bm86** [comment]
sorry for the misunderstanding :sweat_smile: 

i think you should put `comp` inside a pair of parenthesis like

![snapshot](https://cloud.githubusercontent.com/assets/6234553/14225232/9ee52b1e-f8ed-11e5-979d-e6ff4830fcd4.gif)

and just type the single word `comp` indeed will not show the pretty comp symbol. in which context will you want to conceal standalone `comp` word?

**Comment by swr1bm86** [comment]
btw, most pretty symbols in this plugin will not show up when you type single word e.g. `and`, `or`, `def` etc. cause it has no sematic meaning from my perspective.

**Comment by Engelberg** [comment]
I get that it has to be in parens.  (comp + *) does nothing for me.  I have
some checkboxes checked in the settings, and others unchecked.  comp is one
that I have checked, but it doesn't work.  Perhaps that checkbox isn't
properly wired up?

**Comment by swr1bm86** [comment]
woops, i find where the bug is :scream:.  i just mixed up `doseq` and `comp` checkbox, so embrassing :sweat_smile:, i will fix this and check other settings to make sure no more mistakes like this, you won't wait too lone.

**Comment by swr1bm86** [comment]
@Engelberg this is fixed and time to update the plugin :smile:
